Traceback (most recent call last):
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 2380, in get_attr
    c_api.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'truediv_25' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/gradients_util.py", line 345, in _MaybeCompile
    xla_compile = op.get_attr("_XlaCompile")
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 2384, in get_attr
    raise ValueError(str(e))
ValueError: Operation 'truediv_25' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asl_example.py", line 48, in <module>
    runtime, avb = run("asldata_diff.nii.gz", model, outdir, mask="ardtest_mask.nii.gz", **options)
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/avb/main.py", line 221, in run
    runtime, _ret = _runtime(avb.run, record_history=history, **kwargs)
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/avb/main.py", line 319, in _runtime
    ret = runnable(*args, **kwargs)
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/avb/avb.py", line 303, in run
    self._build_graph(use_adam, **kwargs)
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/avb/avb.py", line 298, in _build_graph
    self.grads_and_vars = self.optimizer.compute_gradients(self.cost)
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/training/optimizer.py", line 512, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/gradients_impl.py", line 158, in gradients
    unconnected_gradients)
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/gradients_util.py", line 679, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/gradients_util.py", line 350, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/gradients_util.py", line 679, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/math_grad.py", line 1295, in _RealDivGrad
    grad * math_ops.realdiv(math_ops.realdiv(-x, y), y), ry),
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/math_ops.py", line 1564, in reduce_sum
    name=name))
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 11166, in _sum
    name=name)
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1770, in __init__
    control_input_ops)
  File "/home/ibmeuser/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1607, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
